"""Application katmanının dış dünyaya ihtiyaç duyduğu portlar (Dependency Inversion)."""

from typing import Protocol

from app.domain.repositories import RefreshTokenRepository, UserRepository
from app.domain.user import User


class IdentityUnitOfWork(Protocol):
    users: UserRepository
    refresh_tokens: RefreshTokenRepository

    def __enter__(self) -> "IdentityUnitOfWork": ...
    def __exit__(self, *args) -> None: ...
    def commit(self) -> None: ...
    def track(self, aggregate) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password_hash: str, password: str) -> bool: ...
    def needs_rehash(self, password_hash: str) -> bool: ...


class AccessTokenIssuer(Protocol):
    def issue(self, user: User) -> tuple[str, int]:
        """(token, expires_in_seconds)"""
        ...


class RefreshTokenGenerator(Protocol):
    def generate(self) -> str: ...
    def hash(self, raw_token: str) -> str: ...


class TokenRevocationStore(Protocol):
    def revoke_access_token(self, jti: str, ttl_seconds: int) -> None: ...


class LoginThrottle(Protocol):
    def is_locked(self, key: str) -> bool: ...
    def register_failure(self, key: str) -> None: ...
    def reset(self, key: str) -> None: ...
