apiVersion: 1

policies:
  - orgId: 1
    receiver: email-security
    group_by: ["alertname"]
    routes:
      - receiver: email-security
        object_matchers:
          - ["alertname", "=", "LoginBruteForceSuspectedUser"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
