apiVersion: v1
kind: ConfigMap
metadata:
  name: devblog-config
data:
  ENVIRONMENT: production
  LOG_LEVEL: INFO
  DB_HOST: mssql
  DB_PORT: "1433"
  DB_USER: sa
  JWT_ISSUER: devblog-identity
  JWT_AUDIENCE: devblog-api
  COOKIE_SECURE: "true"
