apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devblog
labels:
  - pairs: { app.kubernetes.io/managed-by: kustomize }
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - ingress.yaml
  - policies/network-policies.yaml
  - apps/identity-service.yaml
  - apps/post-service.yaml
  - apps/comment-service.yaml
  - apps/activity-worker.yaml
  - apps/frontend.yaml
  - apps/gateway.yaml
